repos:
-   repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint jenkify
        language: python
        types: [python]
      - id: pytest
        name: pytest
        entry: poetry run pytest tests
        language: python
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
